# Generated by Django 5.0.4 on 2024-04-16 19:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Home", "0008_alter_file_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="github",
            field=models.CharField(max_length=122, null=True),
        ),
        migrations.AddField(
            model_name="form",
            name="leetcode",
            field=models.CharField(max_length=122, null=True),
        ),
        migrations.AddField(
            model_name="form",
            name="linkedin",
            field=models.CharField(max_length=122, null=True),
        ),
        migrations.AddField(
            model_name="form",
            name="projects",
            field=models.CharField(max_length=122, null=True),
        ),
    ]
